import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

// Convert country name to ISO country code for flag API
export function getCountryCode(countryName: string): string {
  const countryToCode: { [key: string]: string } = {
    // North America
    'United States': 'us',
    'United States of America': 'us',
    'USA': 'us',
    'Canada': 'ca',
    'Mexico': 'mx',
    'Guatemala': 'gt',
    'Belize': 'bz',
    'El Salvador': 'sv',
    'Honduras': 'hn',
    'Nicaragua': 'ni',
    'Costa Rica': 'cr',
    'Panama': 'pa',
    'Cuba': 'cu',
    'Jamaica': 'jm',
    'Haiti': 'ht',
    'Dominican Republic': 'do',
    'Bahamas': 'bs',
    'Barbados': 'bb',
    'Trinidad and Tobago': 'tt',
    'Saint Lucia': 'lc',
    'Saint Vincent and the Grenadines': 'vc',
    'Grenada': 'gd',
    'Antigua and Barbuda': 'ag',
    'Dominica': 'dm',
    'Saint Kitts and Nevis': 'kn',
    'Puerto Rico': 'pr',
    'Greenland': 'gl',
    
    // South America
    'Brazil': 'br',
    'Argentina': 'ar',
    'Chile': 'cl',
    'Colombia': 'co',
    'Peru': 'pe',
    'Venezuela': 've',
    'Ecuador': 'ec',
    'Bolivia': 'bo',
    'Paraguay': 'py',
    'Uruguay': 'uy',
    'Guyana': 'gy',
    'Suriname': 'sr',
    'French Guiana': 'gf',
    'Falkland Islands': 'fk',
    
    // Europe - Western
    'United Kingdom': 'gb',
    'UK': 'gb',
    'Great Britain': 'gb',
    'England': 'gb',
    'Scotland': 'gb',
    'Wales': 'gb',
    'Northern Ireland': 'gb',
    'Germany': 'de',
    'France': 'fr',
    'Italy': 'it',
    'Spain': 'es',
    'Netherlands': 'nl',
    'Belgium': 'be',
    'Switzerland': 'ch',
    'Austria': 'at',
    'Luxembourg': 'lu',
    'Monaco': 'mc',
    'Liechtenstein': 'li',
    'Andorra': 'ad',
    'San Marino': 'sm',
    'Vatican': 'va',
    'Vatican City': 'va',
    'Malta': 'mt',
    
    // Europe - Northern
    'Sweden': 'se',
    'Norway': 'no',
    'Denmark': 'dk',
    'Finland': 'fi',
    'Iceland': 'is',
    'Faroe Islands': 'fo',
    
    // Europe - Eastern
    'Poland': 'pl',
    'Czech Republic': 'cz',
    'Czechia': 'cz',
    'Slovakia': 'sk',
    'Hungary': 'hu',
    'Romania': 'ro',
    'Bulgaria': 'bg',
    'Ukraine': 'ua',
    'Belarus': 'by',
    'Moldova': 'md',
    'Russia': 'ru',
    'Russian Federation': 'ru',
    'Lithuania': 'lt',
    'Latvia': 'lv',
    'Estonia': 'ee',
    
    // Europe - Southern
    'Portugal': 'pt',
    'Greece': 'gr',
    'Cyprus': 'cy',
    'Turkey': 'tr',
    'Türkiye': 'tr',
    'Albania': 'al',
    'North Macedonia': 'mk',
    'Macedonia': 'mk',
    'Montenegro': 'me',
    'Serbia': 'rs',
    'Kosovo': 'xk',
    'Bosnia and Herzegovina': 'ba',
    'Croatia': 'hr',
    'Slovenia': 'si',
    'Ireland': 'ie',
    'Gibraltar': 'gi',
    
    // Asia - East
    'China': 'cn',
    'Japan': 'jp',
    'South Korea': 'kr',
    'Korea': 'kr',
    'North Korea': 'kp',
    'Mongolia': 'mn',
    'Taiwan': 'tw',
    'Hong Kong': 'hk',
    'Macau': 'mo',
    'Macao': 'mo',
    
    // Asia - Southeast
    'Thailand': 'th',
    'Vietnam': 'vn',
    'Viet Nam': 'vn',
    'Malaysia': 'my',
    'Singapore': 'sg',
    'Indonesia': 'id',
    'Philippines': 'ph',
    'Myanmar': 'mm',
    'Burma': 'mm',
    'Cambodia': 'kh',
    'Laos': 'la',
    'Brunei': 'bn',
    'Timor-Leste': 'tl',
    'East Timor': 'tl',
    
    // Asia - South
    'India': 'in',
    'Pakistan': 'pk',
    'Bangladesh': 'bd',
    'Sri Lanka': 'lk',
    'Nepal': 'np',
    'Bhutan': 'bt',
    'Maldives': 'mv',
    'Afghanistan': 'af',
    
    // Asia - Central
    'Kazakhstan': 'kz',
    'Uzbekistan': 'uz',
    'Turkmenistan': 'tm',
    'Kyrgyzstan': 'kg',
    'Tajikistan': 'tj',
    
    // Asia - Middle East
    'Iran': 'ir',
    'Iraq': 'iq',
    'Saudi Arabia': 'sa',
    'Yemen': 'ye',
    'Oman': 'om',
    'United Arab Emirates': 'ae',
    'UAE': 'ae',
    'Kuwait': 'kw',
    'Qatar': 'qa',
    'Bahrain': 'bh',
    'Jordan': 'jo',
    'Lebanon': 'lb',
    'Syria': 'sy',
    'Israel': 'il',
    'Palestine': 'ps',
    'Georgia': 'ge',
    'Armenia': 'am',
    'Azerbaijan': 'az',
    
    // Africa - North
    'Egypt': 'eg',
    'Libya': 'ly',
    'Tunisia': 'tn',
    'Algeria': 'dz',
    'Morocco': 'ma',
    'Western Sahara': 'eh',
    'Mauritania': 'mr',
    
    // Africa - West
    'Senegal': 'sn',
    'Gambia': 'gm',
    'Guinea-Bissau': 'gw',
    'Guinea': 'gn',
    'Sierra Leone': 'sl',
    'Liberia': 'lr',
    'Ivory Coast': 'ci',
    'Côte d\'Ivoire': 'ci',
    'Ghana': 'gh',
    'Togo': 'tg',
    'Benin': 'bj',
    'Burkina Faso': 'bf',
    'Mali': 'ml',
    'Niger': 'ne',
    'Nigeria': 'ng',
    'Cape Verde': 'cv',
    
    // Africa - Central
    'Cameroon': 'cm',
    'Central African Republic': 'cf',
    'Chad': 'td',
    'Republic of the Congo': 'cg',
    'Congo': 'cg',
    'Democratic Republic of the Congo': 'cd',
    'DRC': 'cd',
    'Equatorial Guinea': 'gq',
    'Gabon': 'ga',
    'Sao Tome and Principe': 'st',
    
    // Africa - East
    'Sudan': 'sd',
    'South Sudan': 'ss',
    'Ethiopia': 'et',
    'Eritrea': 'er',
    'Djibouti': 'dj',
    'Somalia': 'so',
    'Kenya': 'ke',
    'Uganda': 'ug',
    'Rwanda': 'rw',
    'Burundi': 'bi',
    'Tanzania': 'tz',
    'Seychelles': 'sc',
    'Comoros': 'km',
    'Mauritius': 'mu',
    'Madagascar': 'mg',
    'Mayotte': 'yt',
    'Réunion': 're',
    'Reunion': 're',
    
    // Africa - Southern
    'South Africa': 'za',
    'Namibia': 'na',
    'Botswana': 'bw',
    'Zimbabwe': 'zw',
    'Zambia': 'zm',
    'Malawi': 'mw',
    'Mozambique': 'mz',
    'Angola': 'ao',
    'Lesotho': 'ls',
    'Eswatini': 'sz',
    'Swaziland': 'sz',
    
    // Oceania - Australia & New Zealand
    'Australia': 'au',
    'New Zealand': 'nz',
    
    // Oceania - Melanesia
    'Papua New Guinea': 'pg',
    'Fiji': 'fj',
    'Solomon Islands': 'sb',
    'Vanuatu': 'vu',
    'New Caledonia': 'nc',
    
    // Oceania - Micronesia
    'Palau': 'pw',
    'Micronesia': 'fm',
    'Federated States of Micronesia': 'fm',
    'Marshall Islands': 'mh',
    'Kiribati': 'ki',
    'Nauru': 'nr',
    'Guam': 'gu',
    'Northern Mariana Islands': 'mp',
    
    // Oceania - Polynesia
    'Samoa': 'ws',
    'Tonga': 'to',
    'Tuvalu': 'tv',
    'French Polynesia': 'pf',
    'Cook Islands': 'ck',
    'Niue': 'nu',
    'American Samoa': 'as',
    'Wallis and Futuna': 'wf',
    'Tokelau': 'tk',
    
    // Territories
    'Bermuda': 'bm',
    'Cayman Islands': 'ky',
    'British Virgin Islands': 'vg',
    'U.S. Virgin Islands': 'vi',
    'Turks and Caicos Islands': 'tc',
    'Anguilla': 'ai',
    'Montserrat': 'ms',
    'Aruba': 'aw',
    'Curaçao': 'cw',
    'Curacao': 'cw',
    'Sint Maarten': 'sx',
    'Saint Martin': 'mf',
    'Saint Barthélemy': 'bl',
    'Saint Barthelemy': 'bl',
    'Martinique': 'mq',
    'Guadeloupe': 'gp',
    'Jersey': 'je',
    'Guernsey': 'gg',
    'Isle of Man': 'im',
    'Svalbard and Jan Mayen': 'sj',
    'Bouvet Island': 'bv',
    'South Georgia and the South Sandwich Islands': 'gs',
    'Antarctica': 'aq',
    'French Southern Territories': 'tf',
    'Heard Island and McDonald Islands': 'hm',
    'Christmas Island': 'cx',
    'Cocos Islands': 'cc',
    'Norfolk Island': 'nf',
    'Pitcairn Islands': 'pn',
    'Saint Helena': 'sh',
    'Ascension Island': 'sh',
    'Tristan da Cunha': 'sh',
  };

  return countryToCode[countryName] || 'un'; // Default to UN flag
}

// Get flag image URL from country name
export function getFlagUrl(countryName: string): string {
  const code = getCountryCode(countryName);
  return `https://flagcdn.com/w80/${code}.png`;
}
