import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

// Convert country name to ISO country code for flag API
export function getCountryCode(countryName: string): string {
  const countryToCode: { [key: string]: string } = {
    // North America
    'United States': 'us',
    'Canada': 'ca',
    'Mexico': 'mx',
    'Guatemala': 'gt',
    'Belize': 'bz',
    'El Salvador': 'sv',
    'Honduras': 'hn',
    'Nicaragua': 'ni',
    'Costa Rica': 'cr',
    'Panama': 'pa',
    
    // South America
    'Brazil': 'br',
    'Argentina': 'ar',
    'Chile': 'cl',
    'Colombia': 'co',
    'Peru': 'pe',
    'Venezuela': 've',
    'Ecuador': 'ec',
    'Bolivia': 'bo',
    'Paraguay': 'py',
    'Uruguay': 'uy',
    'Guyana': 'gy',
    'Suriname': 'sr',
    'French Guiana': 'gf',
    
    // Europe
    'United Kingdom': 'gb',
    'Germany': 'de',
    'France': 'fr',
    'Italy': 'it',
    'Spain': 'es',
    'Netherlands': 'nl',
    'Sweden': 'se',
    'Norway': 'no',
    'Denmark': 'dk',
    'Finland': 'fi',
    'Switzerland': 'ch',
    'Austria': 'at',
    'Belgium': 'be',
    'Poland': 'pl',
    'Czech Republic': 'cz',
    'Hungary': 'hu',
    'Romania': 'ro',
    'Bulgaria': 'bg',
    'Croatia': 'hr',
    'Serbia': 'rs',
    'Bosnia and Herzegovina': 'ba',
    'Montenegro': 'me',
    'Slovenia': 'si',
    'Slovakia': 'sk',
    'Ireland': 'ie',
    'Portugal': 'pt',
    'Greece': 'gr',
    'Albania': 'al',
    'North Macedonia': 'mk',
    'Lithuania': 'lt',
    'Latvia': 'lv',
    'Estonia': 'ee',
    'Belarus': 'by',
    'Ukraine': 'ua',
    'Moldova': 'md',
    'Russia': 'ru',
    'Iceland': 'is',
    'Luxembourg': 'lu',
    'Malta': 'mt',
    'Cyprus': 'cy',
    
    // Asia
    'China': 'cn',
    'Japan': 'jp',
    'South Korea': 'kr',
    'North Korea': 'kp',
    'India': 'in',
    'Pakistan': 'pk',
    'Bangladesh': 'bd',
    'Sri Lanka': 'lk',
    'Nepal': 'np',
    'Bhutan': 'bt',
    'Myanmar': 'mm',
    'Thailand': 'th',
    'Vietnam': 'vn',
    'Laos': 'la',
    'Cambodia': 'kh',
    'Malaysia': 'my',
    'Singapore': 'sg',
    'Indonesia': 'id',
    'Philippines': 'ph',
    'Taiwan': 'tw',
    'Mongolia': 'mn',
    'Afghanistan': 'af',
    'Iran': 'ir',
    'Iraq': 'iq',
    'Turkey': 'tr',
    'Saudi Arabia': 'sa',
    'UAE': 'ae',
    'Qatar': 'qa',
    'Kuwait': 'kw',
    'Bahrain': 'bh',
    'Oman': 'om',
    'Yemen': 'ye',
    'Jordan': 'jo',
    'Lebanon': 'lb',
    'Syria': 'sy',
    'Israel': 'il',
    'Palestine': 'ps',
    'Georgia': 'ge',
    'Armenia': 'am',
    'Azerbaijan': 'az',
    'Kazakhstan': 'kz',
    'Uzbekistan': 'uz',
    'Turkmenistan': 'tm',
    'Kyrgyzstan': 'kg',
    'Tajikistan': 'tj',
    
    // Africa
    'Egypt': 'eg',
    'Libya': 'ly',
    'Tunisia': 'tn',
    'Algeria': 'dz',
    'Morocco': 'ma',
    'Sudan': 'sd',
    'South Sudan': 'ss',
    'Ethiopia': 'et',
    'Kenya': 'ke',
    'Uganda': 'ug',
    'Tanzania': 'tz',
    'Rwanda': 'rw',
    'Burundi': 'bi',
    'Democratic Republic of the Congo': 'cd',
    'Republic of the Congo': 'cg',
    'Central African Republic': 'cf',
    'Chad': 'td',
    'Niger': 'ne',
    'Nigeria': 'ng',
    'Cameroon': 'cm',
    'Ghana': 'gh',
    'Ivory Coast': 'ci',
    'Burkina Faso': 'bf',
    'Mali': 'ml',
    'Senegal': 'sn',
    'Guinea': 'gn',
    'Sierra Leone': 'sl',
    'Liberia': 'lr',
    'South Africa': 'za',
    'Namibia': 'na',
    'Botswana': 'bw',
    'Zimbabwe': 'zw',
    'Zambia': 'zm',
    'Malawi': 'mw',
    'Mozambique': 'mz',
    'Madagascar': 'mg',
    'Mauritius': 'mu',
    'Angola': 'ao',
    'Gabon': 'ga',
    'Equatorial Guinea': 'gq',
    'Sao Tome and Principe': 'st',
    
    // Oceania
    'Australia': 'au',
    'New Zealand': 'nz',
    'Papua New Guinea': 'pg',
    'Fiji': 'fj',
    'Solomon Islands': 'sb',
    'Vanuatu': 'vu',
    'Samoa': 'ws',
    'Tonga': 'to',
    'Palau': 'pw',
    'Marshall Islands': 'mh',
    'Micronesia': 'fm',
    'Kiribati': 'ki',
    'Tuvalu': 'tv',
    'Nauru': 'nr',
  };

  return countryToCode[countryName] || 'un'; // Default to UN flag
}

// Get flag image URL from country name
export function getFlagUrl(countryName: string): string {
  const code = getCountryCode(countryName);
  return `https://flagcdn.com/w80/${code}.png`;
}
