project_id = "znkvwgwijwmeapcyjpgu"

[functions.weatherza-chat]
verify_jwt = false

[functions.execute-code]
verify_jwt = false

[functions.execute-visual-python]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.gemini-proxy]
verify_jwt = false

[functions.internet-search]
verify_jwt = false

[functions.weather-proxy]
verify_jwt = false

[functions.pixabay-proxy]
verify_jwt = false

[functions.stock-proxy]
verify_jwt = false

[functions.agent-os]
verify_jwt = false
