project_id = "znkvwgwijwmeapcyjpgu"

[functions.weatherza-chat]
verify_jwt = false

[functions.execute-code]
verify_jwt = false

[functions.execute-visual-python]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
